import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "@/app/global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-2 p-2">
          <Link href="/" className="p-2 bg-blue-400 rounded">Home</Link>
          <Link href="/notes" className="p-2 bg-blue-400 rounded">Notes</Link>
          <Link href="/blog" className="p-2 bg-blue-400 rounded">Blog</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
