import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "@/app/global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-6`}>
        <nav className="flex gap-2">
          <Link href="/" className="rounded bg-blue-400 p-2">
            Home
          </Link>
          <Link href="/notes" className="rounded bg-blue-400 p-2">
            Notes
          </Link>
          <Link href="/blog" className="rounded bg-blue-400 p-2">
            Blog
          </Link>
        </nav>
        <div className="mt-4">{children}</div>
      </body>
    </html>
  );
}
